package exception_Handaling;
public class Test3 {

	public static void main(String[] args) {
		//Scanner s=new Scanner(System.in);
//		int a=s.nextInt();
//		int b=s.nextInt();
		int a=10;
		int b=2;
		try {
			
		
			int result=a/b;
			System.out.println(result);
		}
		catch() {

	}

}
